// data/dummyData.ts
import { GearItem, Category, RentalOrder, User } from './types';

export const dummyCategories: Category[] = [
  { id: 'cat1', name: 'Cycling', description: 'Bicycles and cycling gear' },
  { id: 'cat2', name: 'Camping', description: 'Camping and outdoor gear' },
  { id: 'cat3', name: 'Fitness', description: 'Gym equipment and fitness gear' },
  { id: 'cat4', name: 'Water Sports', description: 'Kayaks, paddleboards, and water gear' },
  { id: 'cat5', name: 'Hiking', description: 'Backpacks, boots, and hiking gear' },
];

export const dummyGear: GearItem[] = [
  {
    id: 'gear1',
    name: 'Mountain Bike Pro',
    description: 'Premium mountain bike with full suspension, suitable for rough terrains.',
    pricePerDay: 35.99,
    brand: 'Trek',
    availability: true,
    stockQuantity: 3,
    images: ['https://placehold.co/400x300/2563eb/white?text=Mountain+Bike'],
    specifications: { frame: 'Aluminum', suspension: 'Full', wheels: '29 inch' },
    categoryId: 'cat1',
    providerId: 'provider1',
    averageRating: 4.8,
    totalReviews: 12,
  },
  {
    id: 'gear2',
    name: 'Road Bike Elite',
    description: 'Lightweight road bike with carbon fiber frame for speed.',
    pricePerDay: 45.99,
    brand: 'Specialized',
    availability: true,
    stockQuantity: 2,
    images: ['https://placehold.co/400x300/16a34a/white?text=Road+Bike'],
    specifications: { frame: 'Carbon Fiber', weight: '8.5 kg' },
    categoryId: 'cat1',
    providerId: 'provider1',
    averageRating: 4.9,
    totalReviews: 8,
  },
  {
    id: 'gear3',
    name: 'Camping Tent - 4 Person',
    description: 'Waterproof dome tent with mesh windows and rainfly.',
    pricePerDay: 19.99,
    brand: 'Coleman',
    availability: true,
    stockQuantity: 5,
    images: ['https://placehold.co/400x300/ea580c/white?text=Camping+Tent'],
    specifications: { capacity: '4 Persons', waterproof: true },
    categoryId: 'cat2',
    providerId: 'provider1',
    averageRating: 4.5,
    totalReviews: 8,
  },
  {
    id: 'gear4',
    name: 'Sleeping Bag - 3 Season',
    description: 'Comfortable sleeping bag for spring, summer, and fall.',
    pricePerDay: 8.99,
    brand: 'Marmot',
    availability: true,
    stockQuantity: 15,
    images: ['https://placehold.co/400x300/7c3aed/white?text=Sleeping+Bag'],
    specifications: { temperature: '10°C to 20°C', season: '3 Season' },
    categoryId: 'cat2',
    providerId: 'provider1',
    averageRating: 4.3,
    totalReviews: 6,
  },
  {
    id: 'gear5',
    name: 'Adjustable Dumbbells Set',
    description: 'Premium adjustable dumbbells with weight range 5-50kg.',
    pricePerDay: 12.99,
    brand: 'Bowflex',
    availability: true,
    stockQuantity: 3,
    images: ['https://placehold.co/400x300/0891b2/white?text=Dumbbells'],
    specifications: { weightRange: '5-50kg', material: 'Cast Iron' },
    categoryId: 'cat3',
    providerId: 'provider1',
    averageRating: 4.9,
    totalReviews: 15,
  },
  {
    id: 'gear6',
    name: 'Yoga Mat Premium',
    description: 'Non-slip eco-friendly yoga mat with carrying strap.',
    pricePerDay: 4.99,
    brand: 'Lululemon',
    availability: true,
    stockQuantity: 20,
    images: ['https://placehold.co/400x300/dc2626/white?text=Yoga+Mat'],
    specifications: { material: 'Natural Rubber', thickness: '5mm' },
    categoryId: 'cat3',
    providerId: 'provider1',
    averageRating: 4.6,
    totalReviews: 20,
  },
  {
    id: 'gear7',
    name: 'Inflatable Kayak - 2 Person',
    description: 'Lightweight inflatable kayak with paddles and pump.',
    pricePerDay: 35.99,
    brand: 'Intex',
    availability: true,
    stockQuantity: 3,
    images: ['https://placehold.co/400x300/2563eb/white?text=Kayak'],
    specifications: { capacity: '2 Persons', material: 'PVC' },
    categoryId: 'cat4',
    providerId: 'provider1',
    averageRating: 4.7,
    totalReviews: 10,
  },
  {
    id: 'gear8',
    name: 'Stand-Up Paddleboard',
    description: 'Premium inflatable SUP with pump and paddle.',
    pricePerDay: 29.99,
    brand: 'iRocker',
    availability: true,
    stockQuantity: 4,
    images: ['https://placehold.co/400x300/16a34a/white?text=Paddleboard'],
    specifications: { length: '10\'6"', width: '32"' },
    categoryId: 'cat4',
    providerId: 'provider1',
    averageRating: 4.8,
    totalReviews: 7,
  },
  {
    id: 'gear9',
    name: 'Hiking Backpack - 60L',
    description: 'Large hiking backpack with hydration system compatibility.',
    pricePerDay: 14.99,
    brand: 'Osprey',
    availability: true,
    stockQuantity: 7,
    images: ['https://placehold.co/400x300/ea580c/white?text=Backpack'],
    specifications: { capacity: '60L', weight: '2.3 kg' },
    categoryId: 'cat5',
    providerId: 'provider1',
    averageRating: 4.4,
    totalReviews: 5,
  },
  {
    id: 'gear10',
    name: 'Hiking Boots - Waterproof',
    description: 'Waterproof hiking boots with ankle support for rugged terrains.',
    pricePerDay: 12.99,
    brand: 'Merrell',
    availability: true,
    stockQuantity: 10,
    images: ['https://placehold.co/400x300/7c3aed/white?text=Boots'],
    specifications: { waterproof: true, material: 'Leather' },
    categoryId: 'cat5',
    providerId: 'provider1',
    averageRating: 4.2,
    totalReviews: 9,
  },
];

export const dummyRentals: RentalOrder[] = [
  {
    id: 'rental1',
    startDate: '2026-07-20T00:00:00.000Z',
    endDate: '2026-07-25T00:00:00.000Z',
    totalPrice: 179.95,
    status: 'RETURNED',
    customerId: 'customer1',
    gearItemId: 'gear1',
    gearItem: dummyGear[0],
  },
  {
    id: 'rental2',
    startDate: '2026-08-01T00:00:00.000Z',
    endDate: '2026-08-05T00:00:00.000Z',
    totalPrice: 99.95,
    status: 'PICKED_UP',
    customerId: 'customer1',
    gearItemId: 'gear3',
    gearItem: dummyGear[2],
  },
  {
    id: 'rental3',
    startDate: '2026-08-10T00:00:00.000Z',
    endDate: '2026-08-12T00:00:00.000Z',
    totalPrice: 25.98,
    status: 'PLACED',
    customerId: 'customer1',
    gearItemId: 'gear6',
    gearItem: dummyGear[5],
  },
  {
    id: 'rental4',
    startDate: '2026-08-15T00:00:00.000Z',
    endDate: '2026-08-20T00:00:00.000Z',
    totalPrice: 179.95,
    status: 'CONFIRMED',
    customerId: 'customer1',
    gearItemId: 'gear7',
    gearItem: dummyGear[6],
  },
];

export const dummyUser: User = {
  id: 'customer1',
  name: 'John Customer',
  email: 'john@customer.com',
  role: 'CUSTOMER',
  isSuspended: false,
};